### ISSUE TITLE
Missing Definitions in SPICE Netlist Causing Hspice Errors

### ISSUE THREAD

**Issue by Scleverlin** [ABKGroup/PROBE3.0#7]
Hello,

I have been working with the PROBE3.0’s SPICE netlist for testing gate circuits using Hspice. But I encountered errors during the simulation due to missing definitions, such as M1 M0 Cmodel. 

It appears that these missing definitions should be generated using Cadence PVS. Unfortunately, we currently do not have access to a Cadence PVS license to generate these ourselves.

Could you please provide the complete SPICE netlist with necessary definitions included? This would greatly help.

Thank you for your assistance!

C.Shi

**Comment by doo3yoon** [comment]
Hello,

I tested HSPICE run with the PROBE3.0 spice netlist file and spice model (PROBE.pm), and checked that it shows errors (M0, M1, and cmodel related error).
Checking ASAP7 spice netlist file as reference, I removed M0, M1, and cmodel column (refer to below) and checked that it runs without error.

![image](https://github.com/ABKGroup/PROBE3.0/assets/102841960/d75d12f8-77db-4950-9142-8432141c6060)

Below are the R and C lines in ASAP7 spice netlist file, which I referred for this test.

![image](https://github.com/ABKGroup/PROBE3.0/assets/102841960/8c732bd3-b5de-4b3d-99d3-c3eff137550a)

Based on this test result and reference format, I think just removing M0, M1, cmodel columns can solve the problem.

Thank you,

Dooseok Yoon
